---

- name: Debian | installing unbound
  apt: "name={{ item }} state=present"
  with_items: "{{ unbound_packages }}"
  when: ansible_os_family == 'Debian'

- name: Debian | installing unbound
  yum: "name={{ item }} state=present"
  with_items: "{{ unbound_packages }}"
  when: ansible_os_family == 'RedHat'

- name: Archlinux | installing unbound
  pacman: "name={{ item }} state=present"
  with_items: "{{ unbound_packages }}"
  when: ansible_os_family == 'Archlinux'

# vim: set ts=2 sw=2:
