---

- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution }}.yml"
      skip: true

- name: Include release specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution_release }}.yml"
      skip: true

- include: install.yml

- name: Configure unbound.conf
  template:
    src: unbound.conf.j2
    dest: "{{ unbound_conf_path }}"

- name: Enable unbound service
  service:
    name: "{{ unbound_service_name }}"
    state: started
    enabled: yes
  when: unbound_enable_service

# vim: set ts=2 sw=2:
