---

- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution }}.yml"
      skip: true

- name: Include release specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution_release }}.yml"
      skip: true

- include: install.yml

- name: Configure unbound.conf
  template:
    src: unbound.conf.j2
    dest: "{{ unbound_conf_path }}"
  notify: reload unbound

- stat:
    path: "{{ unbound_directory }}/unbound_server.key"
  register: unbound_remote_keys
- name: Setup certificates
  command: unbound-control-setup
  when: |
    unbound_control_enable == "yes" and not unbound_remote_keys.stat.exists

- stat:
    path: "{{ unbound_root_hints }}"
  register: unbound_root_hints_file
  when: |
    unbound_root_hints is defined
- name: Download root hints
  get_url:
    url: https://www.internic.net/domain/named.cache
    dest: "{{ unbound_root_hints }}"
  when: |
    unbound_root_hints is defined and not unbound_root_hints_file.stat.exists

# Cannot move this part as the `verify` component of the previous task, because
# unbound-checkconf fails if the file is outside {{ unbound_directory }}
- name: Check unbound.conf
  command: unbound-checkconf "{{ unbound_conf_path }}"
  changed_when: False

- name: Enable unbound service
  service:
    name: "{{ unbound_service_name }}"
    state: started
    enabled: yes
  when: unbound_enable_service

# vim: set ts=2 sw=2:
