---

- file:
    path: "{{ unbound_auto_trust_anchor_file }}"
    state: touch
    mode: "u=rw,g=r,o=r"
    owner: root
    group: root

- name: Update root anchor
  command: unbound-anchor -a "{{ unbound_auto_trust_anchor_file }}"
  changed_when: false

# vim: set ts=2 sw=2:
